apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/var/www/nginx"
      name: storage

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: demo-pvc