apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/local/apache-data
    type: DirectoryOrCreate
