apiVersion: v1
kind: Secret
metadata:
  name: apache-tls
  namespace: apache-prod
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_REAL_CERTIFICATE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_REAL_PRIVATE_KEY
    -----END PRIVATE KEY-----
