apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 2_namespace.yaml
  - 3a_persistent_volume.yaml
  - 3_configmap.yaml
  - 3b_persistent_volume_claim.yaml
  - 4_deployment.yaml
  - 5_service.yaml
  - 6_hpa.yaml
  - 7_ingress.yaml
